// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyZZ28tcez3v8QiyG-TEqFovMSxpv20F4',
    appId: '1:1073276176959:web:585e176451da3886d5c68a',
    messagingSenderId: '1073276176959',
    projectId: 'flutter-video-audio-chat-72df4',
    authDomain: 'flutter-video-audio-chat-72df4.firebaseapp.com',
    storageBucket: 'flutter-video-audio-chat-72df4.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKRmQttVZk-LV8f0DW3EJbuF4ijly7opc',
    appId: '1:1073276176959:android:88d3414fb23b947cd5c68a',
    messagingSenderId: '1073276176959',
    projectId: 'flutter-video-audio-chat-72df4',
    storageBucket: 'flutter-video-audio-chat-72df4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMjy7NzwLI1bz4O4GrVMjyd3phs9mu2f0',
    appId: '1:1073276176959:ios:fde6af58570bd9eed5c68a',
    messagingSenderId: '1073276176959',
    projectId: 'flutter-video-audio-chat-72df4',
    storageBucket: 'flutter-video-audio-chat-72df4.appspot.com',
    iosClientId: '1073276176959-mkq3u0o1il1fl1scq0nkugkgfdvnufv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.just',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMjy7NzwLI1bz4O4GrVMjyd3phs9mu2f0',
    appId: '1:1073276176959:ios:fde6af58570bd9eed5c68a',
    messagingSenderId: '1073276176959',
    projectId: 'flutter-video-audio-chat-72df4',
    storageBucket: 'flutter-video-audio-chat-72df4.appspot.com',
    iosClientId: '1073276176959-mkq3u0o1il1fl1scq0nkugkgfdvnufv9.apps.googleusercontent.com',
    iosBundleId: 'com.example.just',
  );
}
